feat(auth): Establishing the Authentication/Authorization Process with Spring Security
SWM-E2I/wemeet-backend pull request #11
Opened 2023-06-21 09:55 UTC by KAispread

## Related Issue
#9 

## Description
- Spring Security framework 를 사용하여 인증 프로세스를 구현합니다.
- JWT 기반 인증 방식을 사용합니다.

## Screenshots (if appropriate):

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2023-06-21 14:21 UTC, Chaerim1001 requested changes

2023-06-21 14:21 UTC, Chaerim1001 commented on src/main/java/com/e2i/wemeet/config/security/config/SecurityConfig.java
> +                                .requestMatchers("/v1/member").permitAll()
member 프로필 조회에 대한 API도 permitAll로 가져갈 수 있을 것 같습니다.
HttpMethod에 대한 명시도 있으면 더 좋을 것 같습니다 🙌🏻

` requestMatchers(HttpMethod.GET, "/v1/member/**").permitAll()`

2023-06-21 14:21 UTC, Chaerim1001 commented on src/main/java/com/e2i/wemeet/util/validator/CustomFormatValidator.java
> +    private static final String PHONE_REG = "^01(?:0|1|[6-9])[.-]?(\\d{3}|\\d{4})[.-]?(\\d{4})$";
하이픈(-)이 무조건 있거나 혹은 무조건 없도록 하나의 규칙으로 정하면 좋을 것 같다고 생각합니다!

2023-06-21 14:21 UTC, Chaerim1001 commented on src/test/java/com/e2i/wemeet/util/validator/CustomFormatValidatorTest.java
> +}
EOF 🙌🏻

2023-06-22 09:59 UTC, KAispread commented on src/main/java/com/e2i/wemeet/config/security/config/SecurityConfig.java
> +                                .requestMatchers("/v1/member").permitAll()
member 조회는 로그인 된 사용자에게만 허용해야하므로 hasRole(USER)로 검증하는 것이 더 나을것 같아요.
인증 정보 없이도 요청을 허용해야하는 회원 가입이나, SMS 인증만 우선적으로 permitAll 해두었는데 대학 조회 API 같은것들도 이후에 추가해놓을게요!

Http 메소드는 추가해놓겠습니당

2023-06-22 10:01 UTC, KAispread commented on src/main/java/com/e2i/wemeet/util/validator/CustomFormatValidator.java
> +    private static final String PHONE_REG = "^01(?:0|1|[6-9])[.-]?(\\d{3}|\\d{4})[.-]?(\\d{4})$";
번호는 특수문자없이 받도록 하는건 어떨까요? 010823491234

2023-06-22 10:02 UTC, KAispread commented on src/test/java/com/e2i/wemeet/util/validator/CustomFormatValidatorTest.java
> +}
확인했습니다

2023-06-27 06:39 UTC, Chaerim1001 approved these changes
자세한 설명과 주석 덕분에 쉽게 이해할 수 있었습니다! 수고 많으셨어요 🙌🏻

2023-06-27 06:39 UTC, Chaerim1001 commented on src/main/java/com/e2i/wemeet/config/PostConstructor.java
> +    @PostConstruct
개발 테스트를 위한 용도인거죠?!

2023-06-27 13:49 UTC, KAispread commented on src/main/java/com/e2i/wemeet/config/PostConstructor.java
> +    @PostConstruct
아아 넵 맞습니다! 지워서 올려놓을게요 :)

2023-06-27 13:51 UTC, KAispread commented
> 자세한 설명과 주석 덕분에 쉽게 이해할 수 있었습니다! 수고 많으셨어요 🙌🏻

감사합니다! 개발환경에 Redis 구축 후에 Merge 하겠습니다

2023-07-01 15:19 UTC, merged